// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE_hzmaajho4FCkM9gPoKaxTLY9-w78dI',
    appId: '1:950535486393:web:bb4fdfec9750790cbe1468',
    messagingSenderId: '950535486393',
    projectId: 'erm-maxah',
    authDomain: 'erm-maxah.firebaseapp.com',
    storageBucket: 'erm-maxah.firebasestorage.app',
    measurementId: 'G-1SR2R39LRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxlkNdmsYo_W3q-tPG5XvUapAe5IfAaEY',
    appId: '1:950535486393:android:19b27dbbbb3978cabe1468',
    messagingSenderId: '950535486393',
    projectId: 'erm-maxah',
    storageBucket: 'erm-maxah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPND975KEDA3i5MYzqJdrYMRRJo_mQlT8',
    appId: '1:950535486393:ios:aa83abc6f75cb1ccbe1468',
    messagingSenderId: '950535486393',
    projectId: 'erm-maxah',
    storageBucket: 'erm-maxah.firebasestorage.app',
    iosBundleId: 'com.maxah.erm.erm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPND975KEDA3i5MYzqJdrYMRRJo_mQlT8',
    appId: '1:950535486393:ios:aa83abc6f75cb1ccbe1468',
    messagingSenderId: '950535486393',
    projectId: 'erm-maxah',
    storageBucket: 'erm-maxah.firebasestorage.app',
    iosBundleId: 'com.maxah.erm.erm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE_hzmaajho4FCkM9gPoKaxTLY9-w78dI',
    appId: '1:950535486393:web:71ee6d0c883172aebe1468',
    messagingSenderId: '950535486393',
    projectId: 'erm-maxah',
    authDomain: 'erm-maxah.firebaseapp.com',
    storageBucket: 'erm-maxah.firebasestorage.app',
    measurementId: 'G-H6BRG06BDY',
  );
}
